public class Player {
    public void playing(){
        String Player1Name = 'John';
        system.debug(Player1Name);
        Integer Player1Namelength = Player1Name.length();
        system.debug(player1Namelength);
        String upperPlayer1Name = Player1Name.toUpperCase();
        system.debug(upperPlayer1Name);

        String Player2Name = 'Jack';
        system.debug(Player2Name);
        Integer Player2Namelength = Player2Name.length();
        system.debug(player2Namelength);

        String Player3Name = 'Amy';
        system.debug(Player3Name);
        Integer Player3Namelength = Player3Name.length();
        system.debug(player3Namelength);
        String upperPlayer3Name = Player3Name.toUpperCase();
        system.debug(upperPlayer3Name);

        String Player4Name = 'Mary';
        system.debug(Player4Name);
        Integer Player4Namelength = Player4Name.length();
        system.debug(player4Namelength);

        String Player5Name = 'William';
        system.debug(Player5Name);
        Integer Player5Namelength = Player5Name.length();
        system.debug(player5Namelength);
        


    }
}